/*
This file is automatically generated,please don't edit it!!
*/
#include <Platform_Lib/RemoteControl/RemoteControl.h>
#include "../../autoconf.h"
#include "./ir_default.h"

#ifdef CONFIG_IR_AKIRA
#include "IR_AKIRA/AKIRA_Map.h"
#endif 
#ifdef CONFIG_IR_BG02CB
#include "IR_BG02CB/BG02CB_Map.h"
#endif 
#ifdef CONFIG_IR_BOHONG
#include "IR_BOHONG/BOHONG_Map.h"
#endif 
#ifdef CONFIG_IR_BY04CB
#include "IR_BY04CB/BY04CB_Map.h"
#endif 
#ifdef CONFIG_IR_CHANGYI
#include "IR_CHANGYI/CHANGYI_Map.h"
#endif 
#ifdef CONFIG_IR_CX007F
#include "IR_CX007F/CX007F_Map.h"
#endif 
#ifdef CONFIG_IR_CY0152
#include "IR_CY0152/CY0152_Map.h"
#endif 
#ifdef CONFIG_IR_DAEWOO_R03
#include "IR_DAEWOO_R03/DAEWOO_R03_Map.h"
#endif 
#ifdef CONFIG_IR_Datong
#include "IR_Datong/Datong_Map.h"
#endif 
#ifdef CONFIG_IR_HBY
#include "IR_HBY/HBY_Map.h"
#endif 
#ifdef CONFIG_IR_HK10N
#include "IR_HK10N/HK10N_Map.h"
#endif 
#ifdef CONFIG_IR_HKC
#include "IR_HKC/HKC_Map.h"
#endif 
#include "IR_HKFAC/HKFac_map.h"
#ifdef CONFIG_IR_Huanghe
#include "IR_Huanghe/Huanghe_Map.h"
#endif 
#ifdef CONFIG_IR_HUANUOYI
#include "IR_HUANUOYI/HUANUOYI_Map.h"
#endif 
#ifdef CONFIG_IR_Huichen
#include "IR_Huichen/Huichen_Map.h"
#endif 
#ifdef CONFIG_IR_HYMULLER
#include "IR_HYMULLER/HYMULLER_Map.h"
#endif 
#ifdef CONFIG_IR_KETE
#include "IR_KETE/KETE_Map.h"
#endif 
#ifdef CONFIG_IR_KONTECH
#include "IR_KONTECH/KONTECH_Map.h"
#endif 
#ifdef CONFIG_IR_KONTECH0063
#include "IR_KONTECH0063/KONTECH0063_Map.h"
#endif 
#ifdef CONFIG_IR_LSAD28
#include "IR_LSAD28/LSAD28_Map.h"
#endif 
#ifdef CONFIG_IR_OPARMCO
#include "IR_OPARMCO/OPARMCO_Map.h"
#endif 
#ifdef CONFIG_IR_RC530BS
#include "IR_RC530BS/RC530BS_Map.h"
#endif 
#ifdef CONFIG_IR_RCT2401
#include "IR_RCT2401/RCT2401_Map.h"
#endif 
#ifdef CONFIG_IR_RICHINFO
#include "IR_RICHINFO/RichInfo_Map.h"
#endif 
#ifdef CONFIG_IR_RTK_MK5_TV_2
#include "IR_RTK_MK5_TV_2/RTK_MK5_TV_2.h"
#endif 
#ifdef CONFIG_IR_SHZHI
#include "IR_SHZHI/SHZHI_Map.h"
#endif 
#ifdef CONFIG_IR_SKYWORTH
#include "IR_SKYWORTH/SKYWORTH_Map.h"
#endif 
#ifdef CONFIG_IR_SPHERE
#include "IR_SPHERE/SPHERE_Map.h"
#endif 
#ifdef CONFIG_IR_STT_RC051
#include "IR_STT_RC051/STT_RC051_Map.h"
#endif 
#ifdef CONFIG_IR_THS52K
#include "IR_THS52K/THS52K_Map.h"
#endif 
#ifdef CONFIG_IR_VIANO
#include "IR_VIANO/VIANO_Map.h"
#endif 
#ifdef CONFIG_IR_WL306
#include "IR_WL306/WL306_Map.h"
#endif 
#ifdef CONFIG_IR_WMSDUT
#include "IR_WMSDUT/WMSDUT_Map.h"
#endif 
#ifdef CONFIG_IR_XLF_057
#include "IR_XLF_057/XLF_057_Map.h"
#endif 
#ifdef CONFIG_IR_YBTong
#include "IR_YBTong/YBTong_Map.h"
#endif 
#ifdef CONFIG_IR_YLZH
#include "IR_YLZH/YLZH_Map.h"
#endif 
#ifdef CONFIG_IR_YS
#include "IR_YS/YS_Map.h"
#endif 
extern IR_MAP_t stIR_map[];
extern int dIR_map_size;
