/**
 * This file is automatically generated
 * @Author Longqi mail:1218715400@qq.com
 */
#ifndef __LOWLEVEL_PARAM_H
#define __LOWLEVEL_PARAM_H

#include "../../autoconf.h"
#include "./ir_default.h"
// #include "hk_remote.h"

#ifndef __HK_REMOTE_H
#define __HK_REMOTE_H
#include "../../autoconf.h"
#include "./ir_default.h"
#ifdef CONFIG_IR_AKARI 
#include "./IR_AKARI/AKARI_Map.h" 
#endif 
#ifdef CONFIG_IR_AKIRA 
#include "./IR_AKIRA/AKIRA_Map.h" 
#endif 
#ifdef CONFIG_IR_AL46D338 
#include "./IR_AL46D338/AL46D338_Map.h" 
#endif 
#ifdef CONFIG_IR_AL46D9203 
#include "./IR_AL46D9203/AL46D9203_Map.h" 
#endif 
#ifdef CONFIG_IR_ALPHA 
#include "./IR_ALPHA/ALPHA_Map.h" 
#endif 
#ifdef CONFIG_IR_ALTRN 
#include "./IR_ALTRN/ALTRN_Map.h" 
#endif 
#ifdef CONFIG_IR_BD31 
#include "./IR_BD31/BD31_Map.h" 
#endif 
#ifdef CONFIG_IR_C3230 
#include "./IR_C3230/C3230_Map.h" 
#endif 
#ifdef CONFIG_IR_CH0707 
#include "./IR_CH0707/CH0707_Map.h" 
#endif 
#ifdef CONFIG_IR_CHCC 
#include "./IR_CHCC/CHCC_Map.h" 
#endif 
#ifdef CONFIG_IR_CHFAC 
#include "./IR_CHFAC/CHFAC_Map.h" 
#endif 
#ifdef CONFIG_IR_CN22601 
#include "./IR_CN22601/CN22601_Map.h" 
#endif 
#ifdef CONFIG_IR_CX508 
#include "./IR_CX508/CX508_Map.h" 
#endif 
#ifdef CONFIG_IR_CY2200SUNNY 
#include "./IR_CY2200SUNNY/CY2200SUNNY_Map.h" 
#endif 
#ifdef CONFIG_IR_CYED0000 
#include "./IR_CYED0000/CYED0000_Map.h" 
#endif 
#ifdef CONFIG_IR_CYEDR000 
#include "./IR_CYEDR000/CYEDR000_Map.h" 
#endif 
#ifdef CONFIG_IR_CYFAC 
#include "./IR_CYFAC/CYFAC_Map.h" 
#endif 
#ifdef CONFIG_IR_CHAOHONG 
#include "./IR_ChaoHong/ChaoHong_Map.h" 
#endif 
#ifdef CONFIG_IR_GOSONIC 
#include "./IR_GOSONIC/GOSONIC_Map.h" 
#endif 
#ifdef CONFIG_IR_GZGD 
#include "./IR_GZGD/GZGD_Map.h" 
#endif 
#ifdef CONFIG_IR_HDRD19 
#include "./IR_HDRD19/HDRD19_Map.h" 
#endif 
#ifdef CONFIG_IR_HDRE19 
#include "./IR_HDRE19/HDRE19_Map.h" 
#endif 
#ifdef CONFIG_IR_HK10N 
#include "./IR_HK10N/HK10N_Map.h" 
#endif 
#ifdef CONFIG_IR_HKC 
#include "./IR_HKC/HKC_Map.h" 
#endif 
#ifdef CONFIG_IR_HKFAC 
#include "./IR_HKFAC/HKFAC_Map.h" 
#endif 
#ifdef CONFIG_IR_HONGSHENG 
#include "./IR_HONGSHENG/HONGSHENG_Map.h" 
#endif 
#ifdef CONFIG_IR_HUIWEI 
#include "./IR_HUIWEI/HUIWEI_Map.h" 
#endif 
#ifdef CONFIG_IR_HAOWEI 
#include "./IR_HaoWei/HaoWei_Map.h" 
#endif 
#ifdef CONFIG_IR_KIMURA 
#include "./IR_KIMURA/KIMURA_Map.h" 
#endif 
#ifdef CONFIG_IR_KR180004 
#include "./IR_KR180004/KR180004_Map.h" 
#endif 
#ifdef CONFIG_IR_KTRONICS 
#include "./IR_KTRONICS/KTRONICS_Map.h" 
#endif 
#ifdef CONFIG_IR_KXD6122 
#include "./IR_KXD6122/KXD6122_Map.h" 
#endif 
#ifdef CONFIG_IR_MXY 
#include "./IR_MXY/MXY_Map.h" 
#endif 
#ifdef CONFIG_IR_NEC007F 
#include "./IR_NEC007F/NEC007F_Map.h" 
#endif 
#ifdef CONFIG_IR_NEC6122 
#include "./IR_NEC6122/NEC6122_Map.h" 
#endif 
#ifdef CONFIG_IR_PHILCO 
#include "./IR_PHILCO/PHILCO_Map.h" 
#endif 
#ifdef CONFIG_IR_R95K16 
#include "./IR_R95K16/R95K16_Map.h" 
#endif 
#ifdef CONFIG_IR_RH20 
#include "./IR_RH20/RH20_Map.h" 
#endif 
#ifdef CONFIG_IR_RH21 
#include "./IR_RH21/RH21_Map.h" 
#endif 
#ifdef CONFIG_IR_RJK72 
#include "./IR_RJK72/RJK72_Map.h" 
#endif 
#ifdef CONFIG_IR_RS41 
#include "./IR_RS41/RS41_Map.h" 
#endif 
#ifdef CONFIG_IR_SABA 
#include "./IR_SABA/SABA_Map.h" 
#endif 
#ifdef CONFIG_IR_SAMSONIC 
#include "./IR_SAMSONIC/SAMSONIC_Map.h" 
#endif 
#ifdef CONFIG_IR_SS1 
#include "./IR_SS1/SS1_Map.h" 
#endif 
#ifdef CONFIG_IR_SZGC 
#include "./IR_SZGC/SZGC_Map.h" 
#endif 
#ifdef CONFIG_IR_TEAC 
#include "./IR_TEAC/TEAC_Map.h" 
#endif 
#ifdef CONFIG_IR_TEACFAC 
#include "./IR_TEACFAC/TEACFAC_Map.h" 
#endif 
#ifdef CONFIG_IR_TREEVIEW1 
#include "./IR_TREEVIEW1/TREEVIEW1_Map.h" 
#endif 
#ifdef CONFIG_IR_XY 
#include "./IR_XY/XY_Map.h" 
#endif 
#ifdef CONFIG_IR_ZHJP 
#include "./IR_ZHJP/ZHJP_Map.h" 
#endif 
#ifdef CONFIG_IR_ZHJPRS41 
#include "./IR_ZHJPRS41/ZHJPRS41_Map.h" 
#endif 
#endif /* __HK_REMOTE_H */
#define IR_POWERID_0 PHILCO_IR_POWER
#define IR_POWERID_1 HKFAC_IR_POWER
#define IR_POWERID_2 CYFAC_IR_POWER

#endif /* __LOWLEVEL_PARAM_H */
