/**
 * This file is automatically generated
 * @Author Longqi mail:1218715400@qq.com
 */
/* generated at 2019 02 06 11 38 31 */
#ifndef __ORDER_H
#define __ORDER_H

/***Define Custom Key***/
// do not change Kx


#define K1 CMD_POWER // 0x20, 0x3f
#define K2 CMD_CHANNEL_DEC // 0x40, 0x5f
#define K3 CMD_CHANNEL_INC // 0x60, 0x7f
#define K4 CMD_VOL_DOWN // 0x80, 0x9f
#define K5 CMD_VOL_UP // 0xa0, 0xbf
#define LOG_PWR  KEY2RANGE(K1)


/* Define BackLight Value */

/*******************************************************************/
// config Start
// Language
#define ENABLE_OSD_LAN_ENGLISH
//#define ENABLE_OSD_LAN_SPANISH
#define ENABLE_OSD_LAN_PORTUGUESE

// Subtitle
#define TEXT_LANG	1

//The sound curve
//HK_SOUND_T_BOARD2936_E01
//HK_SOUND_T_BOARD2936_E06
//HK_SOUND_T_BOARD2936_V02
//HK_SOUND_T_BOARD2936_P638
//HK_SOUND_T_BOARD2936_P531
#define HK_SOUND_T_BOARD2936_P532

#define ENABLE_FIVE_KEY


#define HOMEORSTORE   0
#define STORE_VAL     0
#define HOME_VAL     20
#define HK_ENBALE_HOTEL_MODE  SET_OFF

//Atv default
#define CUSTOM_VIDEO_SYSTEM	RT_COLOR_STD_PAL_I
#define CUSTOM_AUDIO_SYSTEM	RT_ATV_SOUND_SYSTEM_BG

#endif /* __ORDER_H */
