#!/usr/bin/python
# Author longqi mail:1218715400@qq.com

from __future__ import print_function

# import argparse


genfile = './hikeen/order/custom.config'
filename = './hikeen/script/filename.file'
packgefilehandle = open(filename,'wb') 
genconfigfile = './hikeen/order/custom.config'
getconfigfilevalue = ['BOARD_NAME', 'BOARD_TUNER', 'HK_BOARD_ID', 'BOOT_SPI_RRJ_ID']
getconfigfilefiltervalue = ['null']
genboardfile = ""
getboardvalue = ['BOARD_TUNER']
getboardfiltervalue = ['null']
genmenufile = './.config'
getmenuvalue = ['CONFIG_IRS_TYPE', 'CONFIG_PANELS_TYPE', 'CONFIG_ORDERS_TYPE']
getmenufiltervalue = ['null']
find_index = 0

def genbyequal (linestring):
	if linestring.find('#') == -1:
		return linestring
	return '###'

#def genselect (filehandle,index):
	

def outfile(line):
	if line.find("generated") == -1 and line.find("Longqi") == -1:
		line = line.replace(" ","")
	packgefilehandle.write(line)
	if line.find("BOARD_NAME=") != -1:
		global genboardfile
		genboardfile = line.replace("BOARD_NAME=","")
		genboardfile = './hikeen/common/board/BOARD_' + genboardfile[0:len(genboardfile)-1] + ".config"
		
def genstep1(filename,array,filter):
	filehandle = open(filename,'r') 
	find_index = 0
	find_max = len(array)
	while True :
		linestring = filehandle.readline()
		if linestring == '' or find_index == find_max :
			break
		if linestring.find(array[find_index]) == 0:
			print(find_index)
			find_index = find_index + 1
			print(linestring)
			if linestring.find('=') == 0:
				outfile(linestring)
			else:
				flag = True
				while flag:
					tmp_index = 0
					tmp_line = filehandle.readline()
					while True:
						if tmp_line.find(array[tmp_index]) == 0 :
#							outfile(linestring+'null\n')
							flag = False
							break
						tmp_index = tmp_index + 1
						if  tmp_index == find_max :
							break
					if tmp_line == '':
#						outfile(linestring+'null\n')
						break
					if tmp_line.find('#') == -1:
						linestring = linestring[0:len(linestring)-1]
#						outfile(linestring+' = '+tmp_line)
						break
	
def genstep0(filename,array,filter):
	filehandle = open(filename,'r') 
	filecontext = filehandle.readlines()
	for list_file in filecontext:
		for search in array:
			if list_file.find(search) == 0 :
				if list_file.find('=') != -1:
					outfile(list_file)
				else:
					cmp_flag = False
					for list_temp in filecontext:
						if cmp_flag == True:
							filter_flag = True
							for search_tmp in array:
								if list_temp.find(search_tmp) == 0 :
									cmp_flag = False
								else:
									if list_temp.find('=y') != -1:
										filter_flag = False
										for filte in filter:
											if list_temp.find(filte) == 0:
												filter_flag = True
							if filter_flag == False:
								outline = search.replace('# ','',1)
								outline = outline+'=='
								list_temp = list_temp.replace('CONFIG_','',1)
								outline = outline.replace('==','='+list_temp.replace('=y','',1),1)
								outfile(outline)
						if list_temp.find(search) == 0 :
							cmp_flag = True
	                     
def main():
	outfile("/**\n * This file is automatically generated\n * @Author Longqi mail:1218715400@qq.com\n */\n\n")
	genstep0(genconfigfile, getconfigfilevalue, getconfigfilefiltervalue)
	genstep0(genmenufile, getmenuvalue, getmenufiltervalue)
	genstep0(genboardfile, getboardvalue, getboardfiltervalue)
	packgefilehandle.close()
	
	
if __name__ == "__main__":
    main()
	
	
	
